/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameFollowingRouteImport } from './routes/$username.following'
import { Route as UsernameFollowersRouteImport } from './routes/$username.followers'
import { Route as UsernameStatusTweetIdRouteImport } from './routes/$username.status.$tweetId'

const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameFollowingRoute = UsernameFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => UsernameRoute,
} as any)
const UsernameFollowersRoute = UsernameFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => UsernameRoute,
} as any)
const UsernameStatusTweetIdRoute = UsernameStatusTweetIdRouteImport.update({
  id: '/status/$tweetId',
  path: '/status/$tweetId',
  getParentRoute: () => UsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/$username/followers': typeof UsernameFollowersRoute
  '/$username/following': typeof UsernameFollowingRoute
  '/$username/status/$tweetId': typeof UsernameStatusTweetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/$username/followers': typeof UsernameFollowersRoute
  '/$username/following': typeof UsernameFollowingRoute
  '/$username/status/$tweetId': typeof UsernameStatusTweetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/$username/followers': typeof UsernameFollowersRoute
  '/$username/following': typeof UsernameFollowingRoute
  '/$username/status/$tweetId': typeof UsernameStatusTweetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/$username/followers'
    | '/$username/following'
    | '/$username/status/$tweetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/$username/followers'
    | '/$username/following'
    | '/$username/status/$tweetId'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/$username/followers'
    | '/$username/following'
    | '/$username/status/$tweetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/following': {
      id: '/$username/following'
      path: '/following'
      fullPath: '/$username/following'
      preLoaderRoute: typeof UsernameFollowingRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/$username/followers': {
      id: '/$username/followers'
      path: '/followers'
      fullPath: '/$username/followers'
      preLoaderRoute: typeof UsernameFollowersRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/$username/status/$tweetId': {
      id: '/$username/status/$tweetId'
      path: '/status/$tweetId'
      fullPath: '/$username/status/$tweetId'
      preLoaderRoute: typeof UsernameStatusTweetIdRouteImport
      parentRoute: typeof UsernameRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameFollowersRoute: typeof UsernameFollowersRoute
  UsernameFollowingRoute: typeof UsernameFollowingRoute
  UsernameStatusTweetIdRoute: typeof UsernameStatusTweetIdRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameFollowersRoute: UsernameFollowersRoute,
  UsernameFollowingRoute: UsernameFollowingRoute,
  UsernameStatusTweetIdRoute: UsernameStatusTweetIdRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
